/**
 * Car and model constants.
 *
 * The limits are functions of speed rather than fixed numbers, because that is
 * the defining trait of an F1 car: downforce grows with v², so the faster it
 * goes the harder it can corner and brake.
 */

/**
 * Deliberately an arcade car, not a simulator.
 *
 * The previous values were true F1 figures — 5 g corners, 1.5 g launches — which
 * made the car twitchy and unforgiving with a keyboard. These are toned down for
 * a game feel: still fast and weighty, but the grip is higher relative to the
 * power, the steering is softer, and the limits are gentler, so the car is
 * catchable when it steps out.
 */
export const CAR = {
  /** Mass including driver, kg. */
  mass: 780,
  /** Effective power at the wheels, W. Lower than real — arcade, not qualifying. */
  power: 340_000,
  /** Front-to-rear axle distance, m. */
  wheelbase: 3.6,
  /** Track width, m. */
  trackWidth: 2.0,
  /** Centre-of-gravity height, m — drives load transfer. */
  cgHeight: 0.34,
  /** Mechanical (tyre-only) lateral grip, m/s². Generous, so the car sticks. */
  gripMechanical: 13,
  /** Aerodynamic lateral grip coefficient: adds gripAero·v². Mild. */
  gripAero: 0.0016,
  gripLateralMax: 24,
  /** Mechanical braking deceleration, m/s². */
  brakeMechanical: 18,
  brakeAero: 0.0009,
  brakeMax: 28,
  /** Traction-limited launch acceleration, m/s². */
  tractionLimit: 9,
  /** a_drag = dragCoeff·v². Tuned with power to cap around 250 km/h. */
  dragCoeff: 0.0016,
  /** Downforce as a fraction of weight at speed v: dfCoeff·v². */
  downforceCoeff: 0.00035,
  /** Rolling resistance, m/s². */
  rollingResistance: 0.4,
  /** Top speed, m/s (~250 km/h). */
  vMax: 70,
  /** Maximum steering angle at the road wheel, radians. */
  maxSteerAngle: 0.42,
  /** Steering lock is reduced at speed, or the car is undriveable. */
  steerSpeedFalloff: 0.045,
  /** Steering input rate, units per second. Softer for keyboard control. */
  steerRate: 2.6,
  steerReturnRate: 4.2,
  /** Reverse speed cap, m/s. */
  reverseMax: 10,
} as const;

export const GEARS = [0, 12, 21, 30, 39, 48, 58, 70];
export const RPM_IDLE = 4200;
export const RPM_MIN = 9800;
export const RPM_MAX = 14800;

export const TYRE = {
  /** Cold (set) pressure, psi. */
  coldPressure: 22.5,
  /** Temperature the cold pressure was set at, °C. */
  setTemperature: 20,
  ambient: 24,
  /** Ideal operating window, °C. */
  optimalLow: 90,
  optimalHigh: 110,
  /** Heating per unit of slip energy. Tuned so hard use settles near 105 °C. */
  heatRate: 6.5e-5,
  /** Heat generated by simply rolling under load, added to the slip term. */
  rollingHeat: 0.05,
  /** Cooling toward ambient, per second. */
  coolRate: 0.045,
} as const;

export const SURFACE = {
  /** Slope beyond which the surface counts as off-track, radians. */
  offTrackSlope: 0.4,
} as const;

/**
 * Grip and drag by surface type. The surface under the car is read from the
 * circuit texture each frame (see surface.ts), which is what enforces track
 * limits: leave the asphalt and the grip drops, so pushing too hard through a
 * corner runs you wide onto the grass and costs you time.
 */
export type SurfaceKind = "asphalt" | "kerb" | "grass" | "offtrack";

export const SURFACE_GRIP: Record<SurfaceKind, { grip: number; drag: number }> = {
  asphalt: { grip: 1.0, drag: 0 },
  kerb: { grip: 0.85, drag: 1.4 },
  grass: { grip: 0.5, drag: 3.4 },
  offtrack: { grip: 0.4, drag: 3.8 },
};

/**
 * The car may drive on the racing surface and its kerbs, and nothing else.
 * Everything beyond is walled off by an invisible barrier at the track edge —
 * the car crashes into it rather than driving onto the grass.
 */
export function isDrivable(surface: SurfaceKind): boolean {
  return surface === "asphalt" || surface === "kerb";
}

export const G = 9.80665;

export const lateralGrip = (v: number, gripScale = 1) =>
  Math.min(CAR.gripMechanical + CAR.gripAero * v * v, CAR.gripLateralMax) * gripScale;

export const brakingLimit = (v: number, gripScale = 1) =>
  Math.min(CAR.brakeMechanical + CAR.brakeAero * v * v, CAR.brakeMax) * gripScale;

export const dragDeceleration = (v: number) => CAR.dragCoeff * v * v;

/** Downforce expressed in newtons. */
export const downforce = (v: number) => CAR.downforceCoeff * v * v * CAR.mass * G;

/** Net forward acceleration: tyre-limited low down, power-limited high up. */
export function driveAcceleration(v: number, throttle: number, gripScale = 1): number {
  const speed = Math.max(1, Math.abs(v));
  const powerLimited = CAR.power / (CAR.mass * speed);
  return Math.min(CAR.tractionLimit * gripScale, powerLimited) * throttle;
}

/** Friction ellipse — grip spent turning is unavailable for driving or braking. */
export function combinedLimit(longMax: number, aLat: number, latMax: number): number {
  if (latMax <= 0) return longMax;
  const used = Math.min(1, Math.abs(aLat) / latMax);
  return longMax * Math.sqrt(Math.max(0, 1 - used * used));
}

export function gearAndRpm(v: number): { gear: number; rpm: number } {
  const speed = Math.abs(v);
  let gear = 1;
  for (let i = 1; i < GEARS.length; i++) if (speed >= GEARS[i]) gear = i + 1;
  gear = Math.min(8, gear);
  const lo = GEARS[gear - 1];
  const hi = GEARS[Math.min(gear, GEARS.length - 1)];
  const frac = hi > lo ? Math.min(1, Math.max(0, (speed - lo) / (hi - lo))) : 0;
  const rpm = speed < 2 ? RPM_IDLE : RPM_MIN + frac * (RPM_MAX - RPM_MIN);
  return { gear, rpm };
}

export const msToKmh = (v: number) => v * 3.6;
export const toG = (a: number) => a / G;

export function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || seconds <= 0) return "--:--.---";
  const m = Math.floor(seconds / 60);
  const s = seconds - m * 60;
  return `${m}:${s.toFixed(3).padStart(6, "0")}`;
}
